# General backtest settings
initial_capital: 100000
commission: 0.001  # 0.1%
slippage: 0.0005   # 0.05%
start_date: '2020-01-03'
end_date: ''

# Position sizing and trading thresholds
position_sizing:
  min_position_threshold: 0.05  # Minimum position size to execute trade (1% of capital)
  min_forecast_threshold: 2   # Minimum forecast strength to generate position
  no_trade_buffer: 0.2          # Buffer zone around current position (10% of position)


# Data settings
instruments:
  equity:
    - source: "MarketStack"
      ticker: "PLTR"
    - source: "IBKR"
      ticker: "TSLA"
    - source: "IBKR"
      ticker: "NVDA"



data_settings:
  preprocessing:
    handle_missing: true
    method: 'ffill'
    resample: null  # Options: null, 'D', 'W', 'M'w

# Predefined strategy
strategy:
  ewmac:
    params: [28, 114]
    weight : 0.95
  breakout:
    params: [64]
    weight : 0.05
