# General backtest settings
initial_capital: 100000
commission: 0.001  # 0.1%
slippage: 0.0005   # 0.05%
start_date: '2020-01-01'
end_date: '2022-12-31'

# Position sizing
position_sizing:
  method: 'percent_risk'  # Options: equal, percent_risk, kelly
  risk_per_trade: 0.02    # 2% risk per trade
  max_position_size: 0.25 # Maximum 25% of portfolio in one position

# Risk management
risk_management:
  use_stop_loss: true
  stop_loss_atr_multiplier: 2.0  # Stop loss at 2x ATR
  trailing_stop: false
  take_profit_risk_multiple: 3.0  # Take profit at 3x risk