# Data settings
backtest_services:
  equity:
    - source: "MarketStack"
      ticker: "TSLA"
    - source: "MarketStack"
      ticker: "AAPL"
    - source: "MarketStack"
      ticker: "PLTR"

  # Data preprocessing
  preprocessing:
    handle_missing: true
    method: 'ffill'
    resample: null  # Options: null, 'D', 'W', 'M'w