# Data settings
arcticdb:
  lib_path: '../../arcticdb'
  symbols:
    - 'PLTR'
    - 'TSLA'
    - 'AAPL'
    - 'QQQ'
  # Data preprocessing
  preprocessing:
    handle_missing: true
    method: 'ffill'
    resample: null  # Options: null, 'D', 'W', 'M'